POST https://localhost:7213/employees
Content-Type: application/json

{
    "firstName": "Mark",
    "lastName": "Fishbach",
    "age": 27,
    "startDateTime": "2023-08-08T08:00:00",
    "dateOfBirth": "1996-01-01T11:00:00",
    "skillset": [
        "Communication",
        "Leadership",
        "Fast Learner",
        "Python"
    ]
}


###
GET https://localhost:7213/Employees/ccaac6d5-d529-4796-b7a0-0ccf29b21347