POST https://localhost:7213/employees
Content-Type: application/json

{
    "firstName": "Alex",
    "lastName": "Makedonski",
    "age": 20,
    "startDateTime": "2023-08-08T08:00:00",
    "dateOfBirth": "1996-01-01T11:00:00",
    "skillset": [
        "Communication",
        "Leadership",
        "Fast Learner",
        "Python"
    ]
}


###
GET https://localhost:7213/Employees/66fae24e162dec79f777c642
