@id = 66fae19eac67841c73e60337

PUT https://localhost:7213/employees/{{id}}
Content-Type: application/json

{
    "firstName": "Alex 2",
    "lastName": "Fishbach",
    "age": 27,
    "startDateTime": "2023-08-08T08:00:00",
    "dateOfBirth": "1996-01-01T11:00:00",
    "skillset": [
        "Communication",
        "Leadership",
        "Fast Learner",
        "Python"
    ]
}